fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Ademhaling.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.AlcoholGebruik.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Alert.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.AllergieIntolerantie.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.BarthelIndex.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.BehandelAanwijzing.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Betaler.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Bloeddruk.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Burgerlijkestaat.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Contact.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Contactpersoon.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.DrugsGebruik.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Familieanamnese.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.FunctioneleOfMentaleStatus.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.GlasgowComaScale.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Hartfrequentie.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Levensovertuiging.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Lichaamsgewicht.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Lichaamslengte.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Lichaamstemperatuur.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.MedicatieGebruik.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.MedicatieToediening.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.MedicatieVerstrekking.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.MedicatieVoorschrift.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.MedischHulpmiddel.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Nationaliteit.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.O2Saturatie.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Opleiding.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.OverdrachtConcern.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.OverdrachtGeplandeZorgActiviteit.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.OverdrachtLaboratoriumUitslag.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.OverdrachtTekstUitslag.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.OverdrachtVerrichting.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Patient.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Pijnscore.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Polsfrequentie.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.TabakGebruik.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Vaccinatie.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Voedingsadvies.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Wilsverklaring.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Woonsituatie.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Zorgaanbieder.xml
fhirconsole -oj c:\temp\dcm2fhirlm\nl.zorg.Zorgverlener.xml

